"""extend user model

Revision ID: 183b1de5387e
Revises:
Create Date: 2026-06-07 13:13:31.076366

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "183b1de5387e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("avatar_url", sa.String(length=500), nullable=True))
    op.add_column("user", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.add_column(
        "user",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "user", sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("user", sa.Column("tenant_id", sa.Integer(), nullable=True))
    op.add_column("user", sa.Column("daily_token_limit", sa.Integer(), nullable=True))
    op.add_column("user", sa.Column("daily_token_used", sa.Integer(), nullable=True))
    op.add_column("user", sa.Column("monthly_token_limit", sa.Integer(), nullable=True))
    op.add_column("user", sa.Column("monthly_token_used", sa.Integer(), nullable=True))
    op.add_column("user", sa.Column("total_token_used", sa.BigInteger(), nullable=True))
    op.add_column(
        "user",
        sa.Column(
            "preferences", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column("user", sa.Column("system_prompt", sa.Text(), nullable=True))
    op.add_column(
        "user",
        sa.Column("milvus_collection_prefix", sa.String(length=64), nullable=True),
    )
    op.alter_column("user", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("user", "password", existing_type=sa.VARCHAR(), nullable=False)
    op.create_index(op.f("ix_user_tenant_id"), "user", ["tenant_id"], unique=False)
    op.create_foreign_key(None, "user", "tenant", ["tenant_id"], ["id"])
    # 初始化角色
    op.bulk_insert(
        sa.table(
            "role",
            sa.column("id", sa.Integer),
            sa.column("name", sa.String),
        ),
        [
            {"id": 1, "name": "user"},
            {"id": 2, "name": "manager"},
            {"id": 3, "name": "admin"},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_index(op.f("ix_user_tenant_id"), table_name="user")
    op.alter_column("user", "password", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("user", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("user", "milvus_collection_prefix")
    op.drop_column("user", "system_prompt")
    op.drop_column("user", "preferences")
    op.drop_column("user", "total_token_used")
    op.drop_column("user", "monthly_token_used")
    op.drop_column("user", "monthly_token_limit")
    op.drop_column("user", "daily_token_used")
    op.drop_column("user", "daily_token_limit")
    op.drop_column("user", "tenant_id")
    op.drop_column("user", "last_login_at")
    op.drop_column("user", "updated_at")
    op.drop_column("user", "created_at")
    op.drop_column("user", "is_active")
    op.drop_column("user", "avatar_url")
    # ### end Alembic commands ###
